### ISSUE TITLE
Source file 

### ISSUE THREAD

**Issue by Eomm** [charliegerard/safe-space#3]
Hi,
I would like to read your source code to get some inspiration since this action is very cool! but I found the dist/index file only. 

Do you plan to share the source code? 

Thank you

**Comment by moisadoru** [comment]
https://github.com/charliegerard/safe-space/blob/master/dist/index.js#L9438

**Comment by ibsusu** [comment]
Ahem...

This is such shitty code.  So dumb.

**Comment by charliegerard** [comment]
I refactored and pushed the source file https://github.com/charliegerard/safe-space/blob/master/index.js

**Comment by Eomm** [comment]
Thank you!
